spring.application.name=goldesk
#servidor
server.address=${SERVER_HOST}
server.port=${SERVER_PORT}

# Configuración de Orígenes Permitidos (CORS)
ALLOWED_ORIGINS=${ALLOWED_ORIGINS:*}


# URL de la base de datos
spring.datasource.url=${DB_URL}

# Usuario y contrasena
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASS_DB}

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Para evitar el error de certificados que tuviste antes
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# Tiempo de espera para que no se quede colgado si el servidor no responde
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}